var navs = [{
	"title": "所有商品",
	"icon": "&#xe614;",
	"spread": true,
	"children": [{
		"title": "列表一",
		"icon": "&#xe641;",
		"href": "li1.html"
	}, {
		"title": "列表二",
		"icon": "&#xe63c;",
		"href": "li2.html"
	}, {
		"title": "列表三",
		"icon": "&#xe63c;",
		"href": "li3.html"
	} ]
}, {
	"title": "解决方案",
	"icon": "&#xe62a;",
	"spread": false,
	"children": [{
		"title": "方案一",
		"icon": "&#xe62a;",
		"href": "plan1.html"
	}, {
		"title": "方案二",
		"icon": "&#xe62a;",
		"href": "plan2.html"
	} ]
},  {
	"title": "百度",
	"icon": "&#xe62a;",
	"href": "https://www.baidu.com",
	"spread": false
}, {
	"title": "系统参数",
	"icon": "&#xe62a;",
	"href": "parameters.html",
	"spread": false
}];