var navs = [{
	"title": "系统管理",
	"icon": "&#xe614;",
	"spread": true,
	"children": [{
		"title": "用户管理",
		"icon": "&#xe612;",
		"href": "user.html"
	}, {
		"title": "角色管理",
		"icon": "&#xe658;",
		"href": "role.html"
	}, {
		"title": "权限管理",
		"icon": "&#xe671;",
		"href": "resources.html"
	} ]
}, {
	"title": "解决方案",
	"icon": "&#xe621;",
	"spread": false,
	"children": [{
		"title": "方案一",
		"icon": "&#xe62a;",
		"href": "plan1.html"
	}, {
		"title": "方案二",
		"icon": "&#xe62a;",
		"href": "plan2.html"
	} ]
},  {
	"title": "百度",
	"icon": "&#xe64c;",
	"href": "https://www.baidu.com",
	"spread": false
}, {
	"title": "系统参数",
	"icon": "&#xe62a;",
	"href": "parameters.html",
	"spread": false
},  {
    "title": "百度1",
    "icon": "&#xe64c;",
    "href": "https://www.baidu.com",
    "spread": false
}, {
    "title": "系统参数1",
    "icon": "&#xe62a;",
    "href": "parameters.html",
    "spread": false
},  {
    "title": "百度2",
    "icon": "&#xe64c;",
    "href": "https://www.baidu.com",
    "spread": false
}, {
    "title": "系统参数2",
    "icon": "&#xe62a;",
    "href": "parameters.html",
    "spread": false
},  {
    "title": "百度3",
    "icon": "&#xe64c;",
    "href": "https://www.baidu.com",
    "spread": false
}, {
    "title": "系统参数3",
    "icon": "&#xe62a;",
    "href": "parameters.html",
    "spread": false
},  {
    "title": "百度4",
    "icon": "&#xe64c;",
    "href": "https://www.baidu.com",
    "spread": false
}, {
    "title": "系统参数4",
    "icon": "&#xe62a;",
    "href": "parameters.html",
    "spread": false
}];